const aiComments = [
  "The Cavaliers' thirteen-game streak shows their unreal consistency—amazing how they keep pulling it off! 🏀",
  "Evan Mobley’s clutch three against the Hornets was pure magic—did you see the commentator’s meltdown? 😂",
  "This win over Charlotte proves the Cavs can grind it out even when they’re not at their best—playoff vibes!",
  "Donovan Mitchell’s scoring in the fourth quarter is just insane—carrying the team like a true leader.",
  "The slow starts are worrying, but a 13-game win streak? I’ll take it any day—shows their depth! 🤔",
  "Jarrett Allen dominating the boards against the Hornets was key—second chances win games.",
  "Darius Garland’s playmaking is on another level, setting up everyone perfectly in crunch time.",
  "The media ignoring us might be a blessing—lets the Cavs focus without the hype train derailing them.",
  "Strus starting could shake things up, but Hunter locking down in the playoffs would be clutch.",
  "That free fries promo is wild—has anyone maxed it out yet? Gotta love the fan hustle! 🍟",
  "Mitchell’s free throws in the final seconds against Charlotte were ice-cold—pure skill.",
  "The Cavs’ defense against the Hornets was suffocating—Bickerstaff’s strategy is paying off big time.",
  "Mobley’s growth as a shooter is opening up the floor—opponents can’t ignore him anymore!",
  "Winning 118-117 on the road is gritty—shows the Cavs have that playoff mentality already.",
  "Garland’s vision is unreal, threading needles under pressure—best point guard play I’ve seen!",
  "The bench stepped up huge against Charlotte—depth is gonna carry us far this season.",
  "Allen’s shot-blocking is a wall—Hornets had no chance inside last night.",
  "Thirteen wins in a row feels surreal—can we keep this momentum going? 🤞",
  "The close games are nerve-wracking, but they’re building character for the postseason.",
  "Strus’ energy off the bench is contagious—lifts the whole team’s spirit!",
  "Mitchell’s leadership shines when it counts—turning games around like a boss.",
  "The Hornets fought hard, but the Cavs’ experience sealed the deal in the end.",
  "Garland’s penetration creates so many opportunities—defenses can’t handle him!",
  "Mobley’s rebounding and scoring combo is a nightmare for any big man out there.",
  "The lack of media buzz might help us stay humble—perfect for a deep playoff run.",
  "Allen’s presence in the paint is unstoppable—altering shots left and right!",
  "That last-minute strategy against Charlotte was genius—coaching at its finest.",
  "The Cavs winning ugly is a sign of a championship team—grit over glamour.",
  "Hunter’s defense could be the x-factor in the playoffs—locks down anyone!",
  "Thirteen straight wins is crazy—time to start dreaming of a 70-win season? 😄",
  "Mitchell’s clutch gene is unreal—saves the day every time we need him.",
  "The bench’s scoring against Charlotte was a game-changer—depth is our strength.",
  "Garland’s quick decisions under pressure are a sight to behold—pure talent!",
  "Mobley’s versatility is evolving—watch out, he’s becoming a complete player.",
  "The Hornets’ late push was fun, but the Cavs stayed composed like veterans.",
  "Allen’s rebounding edge gave us the win—second chances are gold!",
  "Strus stretching the floor with threes is a huge boost for the offense.",
  "The Cavs’ mental toughness in close games is playoff-ready—love seeing it!",
  "Mitchell drawing fouls is a skill—free points at the line are clutch.",
  "The defense led by Allen is a fortress—opponents can’t get inside!",
  "Garland’s passing is poetry—sets up the team like a maestro.",
  "Mobley’s footwork in the post is improving—big things coming!",
  "The reduced hype lets the Cavs focus—perfect for a stealth championship run.",
  "Strus’ hustle on both ends is underrated—keeps the energy high!",
  "Thirteen wins show a team united—every player’s buying in!",
  "The Hornets’ effort was valiant, but the Cavs’ poise won out.",
  "Allen’s shot-altering presence changes the game—defenders hesitate!",
  "Mitchell’s scoring versatility is a matchup nightmare—unstoppable!",
  "The bench’s intensity against Charlotte was key—ready for more!",
  "Garland’s ball-handling under pressure is elite—leads with confidence.",
  "Mobley’s double-threat style is a problem for any defense out there.",
  "The Cavs’ road win over Charlotte builds confidence for the playoffs.",
  "Strus’ three-point shooting opens up the whole offense—smart play!",
  "Thirteen straight is a milestone—let’s keep the streak alive! 🎉",
  "The close victory shows resilience—perfect prep for tough matchups.",
  "Mitchell’s leadership off the court is as strong as his game on it.",
  "Allen’s rebounding tenacity is a game-changer—second shots matter!",
  "The Hornets’ collapse was due to the Cavs’ relentless defense.",
  "Garland’s accuracy under pressure is a skill we can bank on.",
  "Mobley’s growth is exciting—future All-Star in the making!",
  "The bench’s readiness against Charlotte is a sign of a deep roster.",
  "Strus’ defensive rotations are tightening—big help on that end!",
  "The Cavs’ balanced attack is why they’re winning—team effort!",
  "Mitchell’s clutch scoring turns games—can’t ask for more!",
  "Allen’s interior dominance is a cornerstone of our success.",
  "The reduced media focus keeps the Cavs grounded—smart move.",
  "Garland’s vision creates opportunities—pure point guard play!",
  "Mobley’s shot-blocking is intimidating—opponents feel it!",
  "The Hornets’ energy was met with Cavs’ experience—lesson learned.",
  "Strus’ versatility is a coach’s dream—lineup options galore!",
  "Thirteen wins in a row is a statement—top team status confirmed.",
  "The close games build toughness—playoffs will test that!",
  "Mitchell’s free-throw accuracy is clutch—icing the game!",
  "Allen’s rebounding gives us life—second chances are huge!",
  "The Cavs’ defense against Charlotte was lockdown—amazing!",
  "Garland’s leadership drives the team—future is bright!",
  "Mobley’s all-around game is evolving—watch out NBA!",
  "The bench’s contribution is vital—depth wins championships.",
  "Strus’ shooting stretches defenses—opens the floor wide!",
  "The Hornets tried, but the Cavs’ poise prevailed—great win!",
  "Mitchell’s scoring bursts are electric—lights out every time!",
  "Allen’s presence inside is a wall—opponents can’t penetrate!",
  "The Cavs’ grit in close games is playoff-ready—love it! 💪",
  "Garland’s quick thinking under pressure is a game-saver.",
  "Mobley’s rebounding and scoring combo is a double threat.",
  "The reduced spotlight lets the Cavs refine their game quietly.",
  "Strus’ energy lifts the team—underrated impact for sure!"
];

module.exports = aiComments;